config/routes.rb
Rails.application.routes.draw do

#Home page
root to: 'sightings#new'

#Create

get '/sightings/new',       :controller => 'sightings', :action => 'new',
                            :as => 'new_sighting'

post '/sightings',          :controller => 'sightings', :action => 'create',
                            :as => 'sightings'

#Read
get '/sightings',           :controller => 'sightings', :action => 'index'

get '/sightings/:id',       :controller => 'sightings', :action => 'show',
                            :as => 'sighting'

# Update:
get '/sightings/:id/edit',  :controller => 'sightings', :action => 'edit',
                            :as => 'edit_sighting'

patch '/sightings/:id',     :controller => 'sightings', :action => 'update'

end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  validates :mobile,
    :format => { with: /\d{3}-\d{3}-\d{4}/, message: "Enter mobile as 999-999-9999"},
    :allow_nil => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  # def home
  # end

  def index
  end

  def show
  end

  def new
    @sighting = Sighting.new
  end

  def create
     @sighting = Sighting.new
     @sighting.latitude = params[:latitude]
     @sighting.longitude = params[:longitude]

    if @sighting.save
      redirect_to edit_sighting_path(@sighting)
    else
      render 'confirm'
    end
  end

  def edit
    @sighting = Sighting.find(params[:id])
  end

  def update
    @sighting = Sighting.find(params[:id])

    @sighting.address = params[:address]
#    params[:look_for_rats]
#    params[:bait]
#    params[:city_record_ok]
    @sighting.description = params[:description]
    @sighting.first_name = params[:first_name]
    @sighting.last_name = params[:last_name]
    @sighting.email = params[:email]
    @sighting.mobile = params[:mobile]

    if @sighting.save
      redirect_to sighting_url, :notice => "Rat reported successfully."
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>RatTracker</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/yeti/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">Rat Tracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/sightings">Sightings</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for @sighting, :html => { :class => "form-horizontal" } do |f| %>

  <!-- Label and input for location -->
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.text_field :address, :class => "form-control", :placeholder => "Address goes here" %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Submit", :class => "btn btn-success" %>
      or
      <%= link_to "Go back", new_sighting_path %>
    </div>
  </div>

  <!-- Label and input for description -->
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.text_area :description, :class => "form-control", :placeholder => "Details: number of rats, if you see a nest, etc." %>
    </div>
  </div>

  <!-- Label and input for first_name -->
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.text_field :first_name, :class => "form-control", :placeholder => "First name" %>
    </div>
  </div>

  <!-- Label and input for last_name -->
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.text_field :last_name, :class => "form-control", :placeholder => "Last name" %>
    </div>
  </div>

  <!-- Label and input for email -->
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.text_field :email, :class => "form-control", :placeholder => "Email address" %>
    </div>
  </div>

  <!-- Label and input for mobile -->
  <div class="form-group">
    <div class="col-sm-10">
    <%= f.text_field :mobile, :class => "form-control", :placeholder => "Phone (888-888-8888)" %>
    </div>
  </div>

  <!-- Label and input for look_for_rats -->
  <div class="form-group">
    <%= f.hidden_field :look_for_rats, :class => "form-control" %>
  </div>

  <!-- Label and input for bait -->
  <div class="form-group">
    <%= f.hidden_field :bait, :class => "form-control" %>
  </div>

  <!-- Label and input for city_record_ok -->
  <div class="form-group">
    <%= f.hidden_field :city_record_ok, :class => "form-control" %>
  </div>
  <% end %>
</div>

app/views/sightings/confirm.html.erb
<h3>You're done! If you want to add additional info you can.</h3>
<h3>Otherwise, submit!</h3>


<!-- Validation failure messages -->

<% if @sighting.errors.any? %>
<% @sighting.errors.full_messages.each do |message| %>
<div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= message %>
</div>
<% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <!-- <div class="panel panel-default"> -->
    <div class="panel-body">
      <%= form_tag sightings_url, :method => "post", :class => "form-horizontal" do %>
      <!-- Label and input for description -->
      <div class="form-group">
        <label for="description" class="col-sm-2 control-label">
          Description
        </label>
        <div class="col-sm-10">
          <textarea id="description" name="description" placeholder="Description" class="form-control" rows="3"><%= @sighting.description %></textarea>
        </div>
      </div>

      <!-- Label and input for first_name -->
      <div class="form-group">
        <label for="first_name" class="col-sm-2 control-label">
          First name
        </label>
        <div class="col-sm-10">
          <input type="text" id="first_name" name="first_name" placeholder="First name" class="form-control" value="<%= @sighting.first_name %>">
        </div>
      </div>

      <!-- Label and input for last_name -->
      <div class="form-group">
        <label for="last_name" class="col-sm-2 control-label">
          Last name
        </label>
        <div class="col-sm-10">
          <input type="text" id="last_name" name="last_name" placeholder="Last name" class="form-control" value="<%= @sighting.last_name %>">
        </div>
      </div>

      <!-- Label and input for email -->
      <div class="form-group">
        <label for="email" class="col-sm-2 control-label">
          Email
        </label>
        <div class="col-sm-10">
          <input type="text" id="email" name="email" placeholder="Email" class="form-control" value="<%= @sighting.email %>">
        </div>
      </div>

      <!-- Label and input for mobile -->
      <div class="form-group">
        <label for="mobile" class="col-sm-2 control-label">
          Mobile <br> To opt-in for text updates
        </label>
        <div class="col-sm-10">
          <input type="text" id="mobile" name="mobile" placeholder="999-999-9999" class="form-control" value="<%= @sighting.mobile %>">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <input type="submit" value="Submit" class="btn btn-success">
          or
          <a href="/">Cancel</a>
        </div>
      </div>

      <!-- Label and input for location -->
      <div class="form-group">
        <label for="location" class="col-sm-2 control-label">
          Location
        </label>
        <div class="col-sm-10">
          <input type="text" id="location" name="location" placeholder="Location" class="form-control" value="<%= @sighting.location%>">
        </div>
      </div>

      <!-- Label and input for search -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label for="search">
              <input type="checkbox" id="search" name="search" value="1" <%= "checked" if @sighting.search %>>
              Search
            </label>
          </div>
        </div>
      </div>

      <!-- Label and input for bait -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label for="bait">
              <input type="checkbox" id="bait" name="bait" value="1" <%= "checked" if @sighting.bait %>>
              Bait
            </label>
          </div>
        </div>
      </div>

      <!-- Label and input for public -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label for="city_record_ok">
              <input type="checkbox" id="city_record_ok" name="city_record_ok" value="1" <%= "checked" if @sighting.city_record_ok %>>
              Public
            </label>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <!-- </div> -->
  </div>
</div>

<!-- End responsive panel example -->

app/views/sightings/edit.html.erb
<h3>Does the address look good? Cool, hit submit!</h3>
<h3>If you want to add more info you can.</h3>
<h4><small>(The report is public record)</small></h4>



<!-- Validation failure messages -->

<% if @sighting.errors.any? %>
<% @sighting.errors.full_messages.each do |message| %>
<div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= message %>
</div>
<% end %>
<% end %>

<!-- Responsive panel example -->



<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <!-- <div class="panel panel-default"> -->
    <div class="panel-body">
    <%= render 'form', :sighting=> @sighting %>
  </div>
</div>

app/views/sightings/index.html.erb
<h1>Current rat complaints in Chicago</h1>


<p class = "text-center">
<%=image_tag "rat_map.gif", :width => "80%", :class => "thumbnail"%>
  </p>

app/views/sightings/new.html.erb
<style type="text/css">
  .footer {position: fixed; left: 0px;bottom: 0px; height: 30px; width: 100%}
</style>

<div style= "text-align: center" >

  <h1 class="text-center"> <strong>See a rat?</strong></h1>
  <h3 class="text-center">Click and report it!</h3>
  <div class col>
    <%= form_tag sightings_path, id: "sighting-form" do %>
    <%= hidden_field_tag :latitude, "", id: "latitude" %>
    <%= hidden_field_tag :longitude, "", id: "longitude" %>
    <%= image_tag "rat.gif", :width => "50%", onclick: "getLocation()" %>
    <% end %>
  </div>



  <%#= link_to (image_tag"rat tracker.gif", :width => 500), new_sighting_url%>
  <%=image_tag "skyline_2.gif", :width => "100%"%>
</div>

<script>
  var $latitudeField = $("#latitude");
  var $longitudeField = $("#longitude");

  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(addPositionsToForm);
    }
  }

  function addPositionsToForm(position) {
    $latitudeField.val(position.coords.latitude);
    $longitudeField.val(position.coords.longitude);
    $('#sighting-form').submit();
  }
</script>

app/views/sightings/show.html.erb
<h1>You're all done!</h1>

<h2>The city will inspect and bait the location within 3 weeks. </h2>

<h3>Thanks for reporting!</h3>

<%=image_tag "facebook.png", :width => "15%"%>
<h6>Share</h6>


<h3>Curious to see where others have reported rats?</h3>

<%=image_tag "rat_map.gif", :width => "80%", :class => "thumbnail"%>